### ISSUE TITLE
cannot load node

### ISSUE THREAD

**Issue by cardenluo** [11dogzi/Comfyui-ergouzi-Nodes#3]
[ComfyUI-Easy-Use] web root: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes\__init__.py", line 41, in <module>
    from .nodes.EGSZJDYS import EGSZJDYS
ImportError: cannot import name 'EGSZJDYS' from 'Comfyui-ergouzi-Nodes.nodes.EGSZJDYS' (F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes\nodes\EGSZJDYS.py)

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes module for custom nodes: cannot import name 'EGSZJDYS' from 'Comfyui-ergouzi-Nodes.nodes.EGSZJDYS' (F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes\nodes\EGSZJDYS.py)

**Comment by ivanoff13** [comment]
![Снимок](https://github.com/user-attachments/assets/3e9f1322-739d-4060-9c97-cca5a6958e09)

**Comment by ivanoff13** [comment]
> [ComfyUI-простой в использовании] веб-корень: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Загружен обратная трассировка (последний вызов): файл "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", строка 1982, в load_custom_node module_spec.loader.exec_module(модуль) Файл "", строка 940, в файле exec_module "", строка 241, в _файле call_with_frames_removed "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes__инициализировать__.py", строка 41, в из .nodes.EGSZJDYS импортирует EGSZJDYS ImportError: не удается импортировать имя 'EGSZJDYS' из 'Comfyui-ergouzi-Nodes.nodes.EGSZJDYS' (F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes\nodes\EGSZJDYS.py)
> 
> Не удается импортировать F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes модуль для пользовательских узлов: не удается импортировать имя 'EGSZJDYS' из 'Comfyui-ergouzi-Nodes.nodes.EGSZJDYS' (F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes\nodes\EGSZJDYS.py)

1.delete folder ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes
2. git clone [https://github.com/11dogzi/Comfyui-ergouzi-DGNJD.git](https://github.com/11dogzi/Comfyui-ergouzi-DGNJD.git?fbclid=IwZXh0bgNhZW0CMTAAAR1vGl1dFgzuVtnjnGx05j5Wr3mImWs1bq1U_hYVgLbPD_zLKQlGY0ag05k_aem_9NwzUR7oAeeQwtrUbHFGPQ)

**Comment by 11dogzi** [comment]
感谢您支持我的代码，但是由于Comfyui只支持英文代码，所以我不得不退回版本，如果你喜欢这套插件，可以安装我持续更新的另一个库https://github.com/11dogzi/Comfyui-ergouzi-DGNJD
